application: lesguillemets-twbots
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /vimorg_scripts
  script: vimorg_scripts/main.py
  login: admin
- url: /colors
  script: colors/colors.py
  login: admin

libraries:
- name: ssl
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest
